package filesystemsimulation;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Jorge & Badilla 
 */
public class MoveWindow extends javax.swing.JFrame {
    FileSystemDirectory root;
    MainWindow parent;    
    List<FileSystemNode> dirFiles;
    Utilities ut = new Utilities();
    /**
     * Creates new form MoveWindow
     */
    public MoveWindow(FileSystemDirectory rootName, MainWindow parent, List<FileSystemNode> dirFiles) {
        initComponents();
        root = rootName;        
        this.parent = parent;
        this.dirFiles = dirFiles;        
        setNodeNames(dirFiles);
    }
    public void setNodeNames(List<FileSystemNode> dirFiles){
        String result = "";       
        for(FileSystemNode f: dirFiles){
            if(f.isDirectory()){
                result += f.getName() + "/\n"; 
            }else{
                result += f.getName() + "\n"; 
            }
            NamejComboBox.addItem(result);
            result = "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovingLabel = new javax.swing.JLabel();
        ToLabel = new javax.swing.JLabel();
        ToTextField = new javax.swing.JTextField();
        RenameButton = new javax.swing.JButton();
        AcceptButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        NamejComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Move file or directory");
        setResizable(false);

        MovingLabel.setText("Moving:");

        ToLabel.setText("To:");

        RenameButton.setText("Rename");
        RenameButton.setEnabled(false);
        RenameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenameButtonActionPerformed(evt);
            }
        });

        AcceptButton.setText("Accept");
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AcceptButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ToLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MovingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RenameButton)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovingLabel)
                    .addComponent(RenameButton)
                    .addComponent(NamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToLabel)
                    .addComponent(ToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CancelButton)
                    .addComponent(AcceptButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RenameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenameButtonActionPerformed
        int fileNameIndex = NamejComboBox.getSelectedIndex();
        //buscar el archivo en files
        FileSystemNode dirFile = dirFiles.get(fileNameIndex);
        RenameWindow windowRename = new RenameWindow(dirFile);
        windowRename.setVisible(true);
    }//GEN-LAST:event_RenameButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        String newPath = ToTextField.getText();
        int fileNameIndex = NamejComboBox.getSelectedIndex();
        //buscar el archivo en files
        FileSystemNode dirFile = dirFiles.get(fileNameIndex);
        //process both paths
        String [] newPathSplit = newPath.split("/");
        String [] actualPathSplit = dirFile.getPath().split("/");
        List<String> newPathList= new ArrayList<String>();
        List<String> actualPathList = new ArrayList<String>();
        for(String node: newPathSplit){
            newPathList.add(node);
        }        
        for(String node: actualPathSplit){
            actualPathList.add(node);
        }
        actualPathList.remove(actualPathList.size()-1); //removing it's own file or dir name
        
        if (newPathList.equals(actualPathList)){ //
            int dialogButton = JOptionPane.YES_NO_OPTION;
            dialogButton = JOptionPane.showConfirmDialog (this, "You are moving to the same directory. Do you want to rename?","INFORMATION", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) {
                RenameButton.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a path different to the origin of the file or directory", "Moving", INFORMATION_MESSAGE );
            }                   
        } /*else {
            
        }*/
        //this.dispose();
    }//GEN-LAST:event_AcceptButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel MovingLabel;
    private javax.swing.JComboBox<String> NamejComboBox;
    private javax.swing.JButton RenameButton;
    private javax.swing.JLabel ToLabel;
    private javax.swing.JTextField ToTextField;
    // End of variables declaration//GEN-END:variables
}
