/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filesystemsimulation;

import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author adria
 */
public class Window_File_Creation extends javax.swing.JFrame {
    FileSystemDirectory root;
    MainWindow parent;
    Utilities ut = new Utilities();
    /**
     * Creates new form Window_File_Creation
     */
    public Window_File_Creation(FileSystemDirectory rootName, MainWindow parent) {
        initComponents();
        root = rootName;        
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_file_name = new javax.swing.JLabel();
        txf_file_name = new javax.swing.JTextField();
        txf_file_extension = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_file_content = new javax.swing.JTextArea();
        lbl_file_content = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        CreateFileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create file");
        setResizable(false);

        lbl_file_name.setText("Name:");

        txa_file_content.setColumns(20);
        txa_file_content.setRows(5);
        jScrollPane1.setViewportView(txa_file_content);

        lbl_file_content.setText("Content:");

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        CreateFileButton.setText("Create file");
        CreateFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFileButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_file_content, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_file_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txf_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_file_extension, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateFileButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_file_name)
                    .addComponent(txf_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_file_extension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_file_content)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CreateFileButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFileButtonActionPerformed
        // TODO add your handling code here:
        if(validateData()){
            if(ut.fileExitstOnDirectory(root, root.getPath(), txf_file_name.getText())){
                JOptionPane.showMessageDialog(this, "There is a file with the same name in this directory", "Error",  ERROR_MESSAGE);
            } else {
               //Memory Load
                String memory = ut.loadDisc();
                //Load the len line
                int lineLenght = ut.lineLenght();
                //Get the input of the text area
                String contenido = txa_file_content.getText(); 
                contenido = contenido.replace("\n", " ");
                //Calculate the necesary lines to store the file      
                double lineasNecesarias = Math.ceil((float)contenido.length()/(float)(lineLenght-1)); //cantidad de líneas vacías que necesita el archivo  
                //Get a possible index value of the first space where we can write
                //String var= "_____\nramas\ncasa_\n_____\n_____\n";
                List<Integer> emptyIndices = ut.getValidEmptyIndexed(memory,(int)lineasNecesarias, lineLenght);
                //        
                if(emptyIndices == null){
                    JOptionPane.showMessageDialog(this, "There is no free space on disc", "Error",  ERROR_MESSAGE);
                }else{
                    //Modify the string memory
                    memory= ut.addFileToMemory(memory,contenido,emptyIndices,lineLenght);
                    //Writting the new memory
                    ut.WriteDisc(memory);
                    //Now we add the file in the logic file system
                    String fileName = (txf_file_name.getText().concat(".")).concat(txf_file_extension.getText());
                    FileSystemFile f = new FileSystemFile(fileName);
                    f.setSize(contenido.length()); //
                    f.setListOfIndices(emptyIndices); //Necesary to remove...
                    root.add(f);
                    this.dispose();            
                    parent.fillTree(root);                
                    JOptionPane.showMessageDialog(this, "The file was added correctly", "File added", INFORMATION_MESSAGE );        
                    parent.setVisible(true);                
                }
            }
        }
             
    }//GEN-LAST:event_CreateFileButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed
       
    private boolean validateData(){
      String strName = txf_file_name.getText();
      String strExt = txf_file_extension.getText();
      String data = txa_file_content.getText();
      if(strName.equals("") || strExt.equals("") || data.equals("")){
          JOptionPane.showMessageDialog(this, "Name can not be null", "Error",  ERROR_MESSAGE);
          return false;
      }else{
          return true;
      }
    }
    
    //public boolean ifExistFile(String name)

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CreateFileButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_file_content;
    private javax.swing.JLabel lbl_file_name;
    private javax.swing.JTextArea txa_file_content;
    private javax.swing.JTextField txf_file_extension;
    private javax.swing.JTextField txf_file_name;
    // End of variables declaration//GEN-END:variables
}
