/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filesystemsimulation;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author adria
 */
public class Window_File_Creation extends javax.swing.JFrame {
    FileSystemDirectory root;
    MainWindow parent;
    /**
     * Creates new form Window_File_Creation
     */
    public Window_File_Creation(FileSystemDirectory rootName, MainWindow parent) {
        initComponents();
        root = rootName;        
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_file_name = new javax.swing.JLabel();
        txf_file_name = new javax.swing.JTextField();
        lbl_file_extension = new javax.swing.JLabel();
        txf_file_extension = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_file_content = new javax.swing.JTextArea();
        lbl_file_content = new javax.swing.JLabel();
        btn_create_file = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create file");
        setResizable(false);

        lbl_file_name.setText("Name:");

        lbl_file_extension.setText("Extention:");

        txa_file_content.setColumns(20);
        txa_file_content.setRows(5);
        jScrollPane1.setViewportView(txa_file_content);

        lbl_file_content.setText("Content:");

        btn_create_file.setText("Create file");
        btn_create_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_fileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_file_content, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txf_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_file_extension, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txf_file_extension, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(btn_create_file, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_file_name)
                    .addComponent(txf_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_file_extension)
                    .addComponent(txf_file_extension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_file_content)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_create_file)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_create_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_fileActionPerformed
        // TODO add your handling code here:
        validateData();      
        //data validada        
        File file = new File("./disc.txt");
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Window_Virtual_Disc_Creation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
        System.out.println("archivo existente");
        try {
            
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String oldLine = "";
            String linea;
            int lineaLen=1;
            while((linea=br.readLine())!=null){
                oldLine.concat(linea);
                lineaLen=linea.length();
            }
            //terminé de leer           
            //modifico el string/disco
            String contenido = txa_file_content.getText();
            double lineasNecesarias = Math.ceil(contenido.length()/lineaLen); //cantidad de líneas vacías que necesita el archivo
            String var = "0123456789012345\n0123456789012345\n________________\n0_______________\n0_______________\n________________\n________________\n";
            int indexOfFirstEmpty = getValidEmpty(var,(int)lineasNecesarias, lineaLen);
            if(indexOfFirstEmpty == -1){
                JOptionPane.showMessageDialog(this, "There is no free space on disc", "Error",  ERROR_MESSAGE);
            }
            //_______
            //_______
            //escribo el disco
//            FileWriter fw = new FileWriter(file);
//            BufferedWriter bw = new BufferedWriter(fw);
//            bw.write(content);
              br.close();
        } catch (IOException ex) {
            Logger.getLogger(Window_Virtual_Disc_Creation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_create_fileActionPerformed
    
    public int getValidEmpty(String disc, int lineasNecesaria, int largoLinea){
        int emptyLines=0;
        int index=-1;
        for(int i = 0; i< disc.length()&& emptyLines<lineasNecesaria ; i+=largoLinea){
            char firstCharLine =disc.charAt(i);
            if(emptyLines==0){
                index = i;
            }
            if(firstCharLine=='_'){
                emptyLines++;
            }else{
                emptyLines=0;
            }
        }
        if(emptyLines < lineasNecesaria){
            index = -1;
        }
        return index;
    }
   
    private void validateData(){
      String strName = txf_file_name.getText();
      String strExt = txf_file_extension.getText();
      String data = txa_file_content.getText();
      if(strName.equals("")){
          JOptionPane.showMessageDialog(this, "Name can not be null", "Error",  ERROR_MESSAGE);
      }  
      if(strExt.equals("")){
          JOptionPane.showMessageDialog(this, "Extention can not be null", "Error",  ERROR_MESSAGE);
      }
      if(data.equals("")){
          JOptionPane.showMessageDialog(this, "Content can not be null", "Error",  ERROR_MESSAGE);
      }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create_file;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_file_content;
    private javax.swing.JLabel lbl_file_extension;
    private javax.swing.JLabel lbl_file_name;
    private javax.swing.JTextArea txa_file_content;
    private javax.swing.JTextField txf_file_extension;
    private javax.swing.JTextField txf_file_name;
    // End of variables declaration//GEN-END:variables
}
